"""Thin async wrapper around the Apify REST API for YouTube transcripts.

Uses the ``streamers/youtube-scraper`` Apify actor to fetch video transcripts.
Communicates via httpx (already a project dependency) rather than the
``apify-client`` SDK — one fewer dependency, consistent with the existing
YouTube Data API client in ``api.py``.
"""

from __future__ import annotations

import logging
import re
from dataclasses import dataclass
from typing import Any

import httpx

_BASE_URL = "https://api.apify.com/v2"
_SYNC_TIMEOUT = httpx.Timeout(300.0)

logger = logging.getLogger(__name__)


class ApifyError(Exception):
    """Raised when an Apify REST API call fails."""


@dataclass(frozen=True)
class ApifyTranscriptResult:
    """Result of a transcript fetch for one video."""

    transcript: str | None
    """Full transcript text (parsed from SRT), None if unavailable."""

    description: str | None
    """Video description from Apify."""

    view_count: int | None
    """View count."""

    duration_seconds: int | None
    """Duration (may be more accurate than the YouTube Data API value)."""


class ApifyClient:
    """Async client for fetching YouTube transcripts via Apify.

    Parameters
    ----------
    token:
        Apify API token.
    actor_id:
        Actor identifier in ``owner/name`` form.  Defaults to
        ``streamers/youtube-scraper``.
    client:
        Optional pre-configured :class:`httpx.AsyncClient`.  If omitted a new
        one is created with a 300-second timeout (matching Apify's server-side
        sync timeout).
    """

    def __init__(
        self,
        token: str,
        *,
        actor_id: str = "streamers/youtube-scraper",
        client: httpx.AsyncClient | None = None,
    ) -> None:
        self._token = token
        # REST URLs use ~ instead of / in actor IDs.
        self._actor_slug = actor_id.replace("/", "~")
        self._client = client or httpx.AsyncClient(base_url=_BASE_URL, timeout=_SYNC_TIMEOUT)
        self._owns_client = client is None

    async def close(self) -> None:
        if self._owns_client:
            await self._client.aclose()

    # ------------------------------------------------------------------
    # Public
    # ------------------------------------------------------------------

    async def fetch_transcript(self, video_url: str) -> ApifyTranscriptResult:
        """Run the actor for a single video URL and return the transcript.

        Uses the synchronous run endpoint to avoid polling:
        ``POST /v2/acts/{actorId}/run-sync-get-dataset-items``

        Returns an :class:`ApifyTranscriptResult`.  The ``transcript`` field is
        ``None`` when no subtitles are available.

        Raises :class:`ApifyError` on HTTP errors or timeouts (408).
        """
        path = f"/acts/{self._actor_slug}/run-sync-get-dataset-items"
        body: dict[str, Any] = {
            "startUrls": [{"url": video_url}],
            "maxResults": 1,
            "downloadSubtitles": True,
            "subtitlesLanguage": "en",
            "preferAutoGeneratedSubtitles": True,
            "proxyConfiguration": {"useApifyProxy": True},
        }

        data = await self._post(path, body)

        if not isinstance(data, list) or len(data) == 0:
            return ApifyTranscriptResult(
                transcript=None,
                description=None,
                view_count=None,
                duration_seconds=None,
            )

        item = data[0]
        return self._extract_result(item)

    # ------------------------------------------------------------------
    # Internal
    # ------------------------------------------------------------------

    async def _post(
        self,
        path: str,
        body: dict[str, Any],
    ) -> Any:
        """Send a POST request with token authentication."""
        try:
            resp = await self._client.post(
                path,
                json=body,
                params={"token": self._token},
            )
            resp.raise_for_status()
        except httpx.HTTPStatusError as exc:
            raise ApifyError(f"Apify API returned {exc.response.status_code} for {path}") from exc
        except httpx.HTTPError as exc:
            raise ApifyError(f"Apify API request failed for {path}") from exc
        return resp.json()

    @classmethod
    def _extract_result(cls, item: dict[str, Any]) -> ApifyTranscriptResult:
        """Extract transcript and metadata from an Apify dataset item."""
        subtitles = item.get("subtitles")
        transcript: str | None = None
        if isinstance(subtitles, list) and len(subtitles) > 0:
            srt_text = subtitles[0].get("srt")
            if isinstance(srt_text, str) and srt_text.strip():
                transcript = cls._parse_srt(srt_text)
                if not transcript:
                    transcript = None

        description = item.get("description") if isinstance(item.get("description"), str) else None

        raw_views = item.get("viewCount")
        view_count: int | None = None
        if isinstance(raw_views, int):
            view_count = raw_views
        elif isinstance(raw_views, str):
            try:
                view_count = int(raw_views)
            except ValueError:
                pass

        raw_duration = item.get("duration")
        duration_seconds: int | None = None
        if isinstance(raw_duration, int):
            duration_seconds = raw_duration
        elif isinstance(raw_duration, str):
            try:
                duration_seconds = int(raw_duration)
            except ValueError:
                pass

        return ApifyTranscriptResult(
            transcript=transcript,
            description=description,
            view_count=view_count,
            duration_seconds=duration_seconds,
        )

    @staticmethod
    def _parse_srt(srt_text: str) -> str:
        """Parse SRT subtitle format into plain text.

        Strips sequence numbers, timestamps, and blank lines.  Also removes
        inline HTML tags that some auto-generated SRT tracks include.
        """
        lines: list[str] = []
        for line in srt_text.splitlines():
            stripped = line.strip()
            if not stripped:
                continue
            # Skip sequence numbers (bare integers).
            if re.match(r"^\d+$", stripped):
                continue
            # Skip timestamp lines.
            if re.match(r"^\d{2}:\d{2}:\d{2}", stripped):
                continue
            # Strip HTML tags.
            cleaned = re.sub(r"<[^>]+>", "", stripped)
            if cleaned:
                lines.append(cleaned)
        return "\n".join(lines)
